# Generated by Django 5.2.8 on 2025-11-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('longitud_km', models.DecimalField(decimal_places=2, help_text='Longitud en kilómetros', max_digits=5)),
                ('vueltas', models.PositiveIntegerField(default=0)),
                ('record_vuelta', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pais', 'nombre'],
            },
        ),
    ]
