# Generated by Django 5.2.8 on 2025-11-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='circuitos/'),
        ),
    ]
