# Generated by Django 5.2.8 on 2025-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('escuderia', models.CharField(blank=True, max_length=100, null=True)),
                ('puntos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('foto', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
