# Generated by Django 5.2.8 on 2025-11-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pilotos/'),
        ),
    ]
