# Generated by Django 5.2.8 on 2025-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuderias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuderia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='escuderias/'),
        ),
        migrations.AlterField(
            model_name='escuderia',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
